services:
  simulation_models_service:
    hostname: simulation_models_service
    container_name: simulation_models_service
    image: simulation_models_service:latest
    expose:
      - "127.0.0.1:8000:8000"
    volumes:
      -  $PWD/static:/static
    networks:
      - simulation_models

  simulation_models_frontend_service:
    image: nginx:alpine
    hostname: simulation_models_frontend_service
    container_name: simulation_models_frontend_service
    ports:
      - "8080:80"
    volumes:
      - $PWD/nginx/static:/usr/share/nginx/html:ro
      - $PWD/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simulation_models_service
    networks:
      - simulation_models

networks:
  simulation_models:
    name: simulation_models_network
    external: true
